<template>
  <div>
    <ul>
      <li class="list-item" v-for="item in items" :key="item.id">
        {{ item.name }}
      </li>
    </ul>

    <div v-if="loading">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        style="
          margin: auto;
          background: none;
          display: block;
          shape-rendering: auto;
        "
        width="50px"
        height="50px"
        viewBox="0 0 100 100"
        preserveAspectRatio="xMidYMid"
      >
        <circle
          cx="50"
          cy="50"
          fill="none"
          stroke="#e15b64"
          stroke-width="10"
          r="35"
          stroke-dasharray="164.93361431346415 56.97787143782138"
        >
          <animateTransform
            attributeName="transform"
            type="rotate"
            repeatCount="indefinite"
            dur="1s"
            values="0 50 50;360 50 50"
            keyTimes="0;1"
          ></animateTransform>
        </circle>
        <!-- [ldio] generated by https://loading.io/ -->
      </svg>
    </div>
    <RefInfinitescrollObserver
      v-else
      @intersect="intersected"
      :options="{ threshold: 0.0 }"
    />
  </div>
</template>

<script>
export default {
  async asyncData() {
    /* limit 쿼리 변경을 해보세요
      limit=30: 초기 데이터가 충분하여 처음부터 몇개의 컨텐츠가 viewport 밖에 있는 경우(스크롤 생기는 경우)
      limit=10: 초기 데이터가 별로없어서 모든 컨텐츠가 viewport 안에 있는 경우
    */
    const res = await fetch(
      `https://jsonplaceholder.typicode.com/comments?_page=1&_limit=40`
    );
    const items = await res.json();
    return { items };
  },
  data() {
    return {
      page: 10,
      items: [],
      loading: false,
    };
  },
  methods: {
    async intersected() {
      this.loading = true;
      const res = await fetch(
        `https://jsonplaceholder.typicode.com/comments?_page=${this.page}&_limit=10`
      );
      const items = await res.json();

      setTimeout(() => {
        this.page++;
        this.items = [...this.items, ...items];
        this.loading = false;
      }, 2000);
    },
  },
};
</script>
